controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
ajax_car_filter:
    path: /ajax/car/filter
    controller: App\Controller\CarController::filterCars